include("${CMAKE_CURRENT_LIST_DIR}/catch2.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/glm.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/sdl.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/opengl.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/glew.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/vulkan.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/vulkan_memory_allocator.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/nlohmann_json.cmake")
